Add sshd port/user in the config file, change curl to nc to support other protos, fix clean rm errors, overall cleanup

diff --git a/tunnel b/tunnel
--- a/tunnel
+++ b/tunnel
@@ -6,57 +6,62 @@ conf_file=~/.tunnel
 
 parse()
 {
-  eval "$1=$(sed -n "s/$1[[:space:]]*=[[:space:]]*\(.*\)/\1/p" $2)"
+  eval "$1=$(sed -n 's/'"$1"'[[:space:]]*=[[:space:]]*\(.*\)/\1/p' "$2")"
 }
 
 check_active_tunnels()
 {
-  ls /tmp/tunnel-*.cfg > /dev/null 2>&1 &&
-    return 0
+  ls /tmp/tunnel-*.cfg > /dev/null 2>&1 && return 0
 
-  echo "No active tunnel"
+  echo 'No active tunnel' >&2
   return 1
 }
 
 check_status()
 {
   for file in /tmp/tunnel-${2:-*}.cfg; do
+    [ ! -f "$file" ] && return 1
     parse local_port "$file"
-    parse ssh_port "$file"
+    parse distant_port "$file"
     parse target "$file"
-    curl -m 2 127.0.0.1:"$local_port" > /dev/null 2>&1
-    "$1" "$?" "$local_port" "$ssh_port"
+    nc -z 127.0.0.1 "$local_port"
+    "$1" "$?" "$local_port" "$distant_port"
   done
 }
 
 print_status()
 {
-  printf "tunnel: %s -> %s (%s)" "$local_port" "$ssh_port" "$target"
+  printf 'tunnel: %s -> %s (%s)' "$local_port" "$distant_port" "$target"
   if [ "$1" -eq 0 ]; then
-    printf '\033[0;32m OK\033[0m\n'
+    printf '\033[0;32m OK'
   else
-    printf '\033[0;31m KO\033[0m\n'
+    printf '\033[0;31m KO'
   fi
+  printf '\033[0m\n'
 }
 
 stop_tunnel()
 {
-  if [ -f "/tmp/tunnel-$1.cfg" ]; then
-    parse pid "/tmp/tunnel-$1.cfg"
+  [ -f /tmp/tunnel-"$1".cfg ] && {
+    parse pid /tmp/tunnel-"$1".cfg
     if [ "$(ps -p "$pid" -o comm=)" = 'ssh' ]; then
-      kill -s TERM "$pid"
+      kill "$pid"
     fi
-  fi
+  }
 }
 
 create_ssh_tunnel()
 {
   if [ "$1" -ne 0 ]; then
     stop_tunnel "$2"
-    ssh -fNL "$2:$target:$3" "$address" >> /tmp/tunnel-"$2".log 2>&1
-    printf "local_port=%s\nssh_port=%s\ntarget=%s\n" "$2" "$3" "$target" > /tmp/tunnel-"$2".cfg
+    if ! ssh -fNL "$2:$target:$3" -p "$ssh_port" "$user"@"$address" >> /tmp/tunnel-"$2".log 2>&1; then
+      printf '\033[0;31mError\033[0m\n - Failed to create tunnel\n' >&2
+      cat /tmp/tunnel-"$2".log >&2
+      return 1
+    fi
+    printf 'local_port=%s\ndistant_port=%s\ntarget=%s\n' "$2" "$3" "$target" > /tmp/tunnel-"$2".cfg
     ps_ouput="$(ps aux)"
-    pid="$(printf '%s' "$ps_ouput" | sed -n "s/[^[:space:]]*[[:space:]]*\([^[:space:]]*\).*ssh -fNL $2.*/\1/p")"
+    pid="$(printf '%s\n' "$ps_ouput" | sed -n 's/[^[:space:]]*[[:space:]]*\([^[:space:]]*\).*ssh -fNL '"$2"'.*/\1/p')"
     printf 'pid=%s\n' "$pid" >> /tmp/tunnel-"$2".cfg
   fi
 }
@@ -64,27 +69,37 @@ create_ssh_tunnel()
 clean()
 {
   if [ "$1" -ne 0 ]; then
-    stop_tunnel "$2"
-    rm /tmp/tunnel-"$2".*
+    stop_tunnel "$2" && rm /tmp/tunnel-"$2".*
   fi
 }
 
 if [ -f "$conf_file" ]; then
   parse address "$conf_file"
+  parse ssh_port "$conf_file"
+  parse user  "$conf_file"
   parse target  "$conf_file"
   : ${target:=localhost}
 else
-  printf "Enter your ssh address\n> "
+  printf 'Enter the ssh address\n> '
   read address
-  printf "Enter your tunnel target\n> "
+  printf 'Enter the ssh address port (default 22)\n> '
+  read ssh_port
+  : "${ssh_port:=22}"
+  printf 'Enter the ssh address user (default %s)\n> ' "$USER"
+  read user
+  : "${user:=$USER}"
+  printf 'Enter the tunnel target\n> '
   read target
-  printf 'address=%s\ntarget=%s\n' "$address" "$target" > ~/.tunnel
+  printf 'address=%s
+ssh_port=%s
+user=%s
+target=%s
+' "$address" "$ssh_port" "$user" "$target" > ~/.tunnel
   echo
 fi
 
 if [ "$#" -lt 1 ]; then
-  check_active_tunnels
-  if [ "$?" -eq 0 ]; then
+  if check_active_tunnels; then
     check_status print_status
   fi
 else
@@ -111,16 +126,16 @@ else
     help|h|--help|-h)
       echo 'Usage: tunnel [options]
 
-      Displays tunnels status when launched with no options.
+Displays tunnels status when launched with no options.
 
-      Options:
+Options:
 
-            local-port  distant-port     creates a tunnel from your your ssh address on distant-port to localhost on local-port
-            stop, s     [local-port]     stops local-port tunnel or all tunnels if no port is specified
-            clean, c    [local-port]     removes local-port tunnel if stopped or all stopped tunnels if no port is specified
-            restart, r  [local-port]     restarts local-port tunnel if stopped or all stopped tunnels if no port is specified
-            config, cfg                  opens the configuration file with your default editor
-      '
+  local-port  distant-port     creates a tunnel from your your ssh address on distant-port to localhost on local-port
+  stop, s     [local-port]     stops local-port tunnel or all tunnels if no port is specified
+  clean, c    [local-port]     removes local-port tunnel if stopped or all stopped tunnels if no port is specified
+  restart, r  [local-port]     restarts local-port tunnel if stopped or all stopped tunnels if no port is specified
+  config, cfg                  opens the configuration file with your default editor
+'
       ;;
     *)
       if [ "$#" -eq 2 ] && [ "$1" -gt 0 ] && [ "$2" -gt 0 ]; then
